version: '3.4'
services:
  vue_postgres:
    container_name: vue_postgres
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testDB
    volumes:
      - flask-app-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  flask_server:
    container_name: flask_server
    build: ./server
    environment:
      - FLASK_ENV=docker
      - DATABASE_URL=vue_postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=vue_flask
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - vue_postgres
    entrypoint: 
      - /app/server/entry_point.sh
  flask_app:
      container_name: flask_app
      build: ./client
      ports:
        - 8080:8080
      volumes:
        - .:/app/client
      depends_on:
        - flask_server
      entrypoint:
        - /client/entry_point.sh
volumes:
  flask-app-db:
    name: flask-app-db
